"""Added timestamp to challenges

Revision ID: 97851acd639f
Revises: 8c17f69465b1
Create Date: 2017-10-28 12:44:48.369504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97851acd639f'
down_revision = '8c17f69465b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_challenge_timestamp'), 'challenge', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_timestamp'), table_name='challenge')
    op.drop_column('challenge', 'timestamp')
    # ### end Alembic commands ###
